name: ETL for NCBI GEO
on:
  workflow_dispatch:
  schedule:
    # Run daily at 5am UTC
    - cron:  '0 5 * * *'

jobs:
  run-extraction:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      AWS_URL_STYLE: ${{ secrets.AWS_URL_STYLE }}
      OMICIDX_BASE_PATH: ${{ secrets.OMICIDX_BASE_PATH }}

    steps:
      - uses: 'actions/checkout@v4'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: uv sync

      - name: Run GEO extraction
        run: uv run oidx geo extract
