name: Daily SQL Runner
on:
  workflow_dispatch:
  schedule:
    # Run daily at 7am UTC
    - cron:  '0 7 * * *'

jobs:
  run-sql:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 300 # 5 hours
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      AWS_URL_STYLE: ${{ secrets.AWS_URL_STYLE }}
      OMICIDX_BASE_PATH: ${{ secrets.OMICIDX_BASE_PATH }}
      PYTHONUNBUFFERED: 1 # Ensure real-time logging output
      LOGURU_LEVEL: DEBUG

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: 'actions/checkout@v4'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: uv sync

      - name: Run SQL
        run: uv run oidx sql run
